name = "crosstooler"
description = "Builds Cross-Compiling GCC Toolchains for Alire"
version = "1.0.0"

authors = ["Charles Eidsness"]
maintainers = ["Charles Eidsness <charles@ccxtechnologies.com>"]
maintainers-logins = ["charleseidsness"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"

executables = ["crosstooler"]

[origin]
commit = "dce16e0d1b981d09031a334637bc9a4a3a995e48"
url = "git+https://github.com//ccxtechnologies/crosstooler"
